---
language: node_js
node_js: "lts/*"

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  yarn: true
  directories:
    - node_modules
    - bower_components
    - .eslintcache
    - $HOME/.cache/bower
    - $HOME/cc

env:
  global:
    - CC_TEST_REPORTER_ID=8374dba960f4074f7f63401636e7e3eecc8820f5d29d1ff6510a23c02461383b
    - SAUCE_USERNAME=nomego
    - secure: IT+UR1zesj9lbeesU8HSmfDt+6ndECt49IjESyTyTveYWTo9jZf0cS8PmguxF/2E39NFe79nCpmSoY7u95mSW++uqyyuD2/CHQJs0ekoEYQqm7BDIXe/rjGQfGl6ST01dhroVVZs9qc06y5vIVEm/mzj0XvDVshiH737ACYlMFNwuwLqzzWvsWB4OGEf82FNi5QwNDqZW4qP6ntqZd8kipa0y14FYF290cN7BlsJmnsBzTC0QQA0THysfa+XiiF/HQrorQ5VBZRFdi2Q3anBC1bQza4HOdKevDkenWQWB4CIWCLnZtKWqmr7iGfMJz+l8rEQavmRrKyclHDoa6t/s9XlVLbdMvvSubh/ITUhVbmX48eb1Hf6Dx4DWfxO7PocAsYDHv3maEEfHMJ8ioI/Lq+L2SUuG75YWA3iyDxSSOAksX0mEQArUhHDLJL/1C0/FSfDvunex2z2wY0+Irf3wrpHtd/wWrILIwbSUNL6WhMFtU0XUEZI+7idQjW8es9tG7Xpd17lvmabKrYGaHwa1frU5VGh13Kd5CFJlK5rqbAMF4XDqbNVbP+wFMRzwfZ+bb1/MDKITnGkPThZr2+rG5ih4qrmIb61+x/DbhsqG0qlZmHaj+wBhn6FTvocoieeboV6SpWqZ//NsVk09gpQezm8AVUbMK+cbUzirBJIL9Y=
    - NEO_CC_URL=https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    - NEO_CC=$HOME/cc/cc-test-reporter

before_script:
  - yarn lint
  - ([[ -e $NEO_CC ]] || curl -L $NEO_CC_URL > $NEO_CC) && chmod +x $NEO_CC
  - $NEO_CC before-build
script:
  - yarn test $([ -z "$SAUCE_ACCESS_KEY"] && echo "--skip-plugin sauce")
  - $NEO_CC after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  slack:
    secure: Gyt368r6w1HlFAzLQbS7VxeDbzKOQYPg7sfIZQ5xD7X0JI0UbxfHtIQx0peME+DaoE7y3FP+/iH2RggwvPVLzx+MPm+t4Jekme+0bpvfbRezzIw/a3Jl60F65pouQmb4tgILcMQ6pXTJWgBzKUJZsUsBbG3tMwpZ0F+oe1IFafBcLKK733oZqu8dm9CSaNYSVirG0qULEGk4AoIMucX4q+LUNF45FbqSRj/PulFoOncYt6FVGKTtEq5OGSXKW7Kg4Dfq/ooDktfr/7LyONs9nhFYE4eR86W45NmvySpbR3eF5rN5UOfcy8cL/74Fj4xmEyPBzxUFNEJSojXcttygY4cUnJy5XzjY50tR7oICAKtDT0fZMso29S4VEDZUbpmJObqH+TCex4lqZ9CMQ57JU+yhtDYg1JaXKhXlbbidabpZFjRWKH7wCTxcDCr2sJNANlCjC7GNjG726S1gU3RXX88Okvd08AYiUTP2UWIgxH0RsLtzB9Odrmk3HMSIFhVER2fyONjH1tA3DyClIFg6q59lfpt2dSE9DtrbKKXiywAgbg7i/i1xph2FlnKF7Ysu9tdb5l0IkjRKMnQa830zJUYTzspvAdClD+c9VfpPFG19C+QtrZPgvLvrL64nByctSUHT6UCq1Vxb7W+Mp6Rg/k4L2tFUkiTVs1yO2LRJucc=
